# Hack fix to force ansible to evaluate the variable, as it may not be in scope in easy-includes
- local_action: command echo {{ easy_bag_store_version }}
  become: no
  register: mod_version

- include_role:
    name: dans.easy-includes
    tasks_from: install_easy_module
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"

- include_role:
    name: dans.easy-includes
    tasks_from: install_cmd
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"

- include_role:
    name: dans.easy-includes
    tasks_from: install_service
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"

- name: Configure application (application.properties)
  replace: dest={{ easy_modules_installation_base_path }}/easy-bag-store/cfg/application.properties
           regexp="^{{ item.key }}.*$"
           replace="{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'staging.base-dir',          value: '{{ easy_bag_store_staging_basedir }}' }
    - { key: 'daemon.external-base-uri',  value: '{{ easy_bag_store_external_base_uri }}' }

- name: Remove default store from stores.properties
  lineinfile:
      dest: "{{ easy_modules_installation_base_path }}/easy-bag-store/cfg/stores.properties"
      line: "default=/var/local/store"
      state: absent
  when: easy_bag_stores_remove_default|bool

- name: Configure application (stores.properties)
  lineinfile:
      dest: "{{ easy_modules_installation_base_path }}/easy-bag-store/cfg/stores.properties"
      line: "{{ item.name }}={{ item.base_dir }}"
  with_items: "{{ easy_bag_stores }}"

- name: Create bag-store base directories
  file:
    path: "{{ item.base_dir }}"
    state: "directory"
    owner: "easy-bag-store"
    group: "easy-bag-store"
    mode: "0775"
  with_items: "{{ easy_bag_stores }}"

- name: Create a staging directory
  file: path="{{ easy_bag_store_staging_basedir }}" state=directory owner=easy-bag-store group=easy-bag-store mode=0775

- name: Make vagrant member of easy-bag-store group
  user: name=vagrant group=easy-bag-store
  when: inventory_hostname == "deasy"

- include_role:
    name: dans.easy-includes
    tasks_from: start_service
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"
