# Hack fix to force ansible to evaluate the variable, as it may not be in scope in easy-includes
- local_action: command echo {{ easy_bag_store_version }}
  become: no
  register: mod_version

- include_role:
    name: dans.easy-includes
    tasks_from: install_easy_module
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"

- include_role:
    name: dans.easy-includes
    tasks_from: install_cmd
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"

- include_role:
    name: dans.easy-includes
    tasks_from: install_service
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"

- name: Configure application
  replace: dest={{ easy_modules_installation_base_path }}/easy-bag-store/cfg/application.properties
           regexp="^{{ item.key }}.*$"
           replace="{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'bag-store.base-dir',  value: '{{ easy_bag_store_basedir }}' }
    - { key: 'staging.base-dir',    value: '{{ easy_bag_store_staging_basedir }}' }

- name: Create bag-store base directory
  file: path="{{ easy_bag_store_basedir }}" state=directory owner=easy-bag-store group=easy-bag-store mode=0775

- name: Create a staging directory
  file: path="{{ easy_bag_store_staging_basedir }}" state=directory owner=easy-bag-store group=easy-bag-store mode=0775

- name: Make vagrant member of easy-bag-store group
  user: name=vagrant group=easy-bag-store
  when: inventory_hostname == "deasy"

- include_role:
    name: dans.easy-includes
    tasks_from: start_service
  vars:
    easy_module_name: "easy-bag-store"
    easy_module_version: "{{ mod_version.stdout }}"
